src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getPriceWt(): ?float
    {
        $coeff = 1+ $this->tva/100;
        return $coeff*$this->price;
    }


    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Class\Cart;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CartController extends AbstractController
{
    #[Route('/mon-panier', name: 'app_cart')]
    public function index(Cart $cart): Response
    {

        return $this->render('cart/index.html.twig',[
            'cart' => $cart->getCart(),
            'totalPriceWt' => $cart->getTotalPriceWt(),
        ]);
    }

    #[Route('/cart/add/{id}', name: 'app_cart_add')]
    public function add($id, ProductRepository $productRepository , Cart $cart,Request $request): Response
    {
        $product = $productRepository->findOneBy(['id' => $id]);
        $cart->addToCart($product);
        $this->addFlash(
            'success',
            'Votre produit a ete bien ajouter au votre panier !'
        );


        return $this->redirect($request->headers->get('referer'));
    }

    #[Route('/cart/increase/{id}', name: 'app_cart_increase')]
    public function increase($id, ProductRepository $productRepository , Cart $cart,Request $request): Response
    {
        $product = $productRepository->findOneBy(['id' => $id]);
        $cart->addToCart($product);
        $this->addFlash(
            'success',
            'Votre produit a ete bien augmenter !'
        );


        return $this->redirect($request->headers->get('referer'));
    }

    #[Route('/cart/decrease/{id}', name: 'app_cart_decrease')]
    public function decrease($id, Cart $cart,Request $request): Response
    {
        $cart->decrease($id);
        $this->addFlash(
            'success',
            'Votre produit a ete bien deminiue de votre panier !'
        );


        return $this->redirectToRoute('app_cart');
    }

    #[Route('/cart/removeAll', name: 'app_cart_removeAll')]
    public function removeAll(Cart $cart): Response
    {

        $cart->removeAllFromCart();
        return $this->redirectToRoute('app_home');
    }
    #[Route('/cart/remove/{id}', name: 'app_cart_remove')]
    public function remove($id, Cart $cart): Response
    {

        $cart->removeFromCart($id);
        return $this->redirectToRoute('app_cart');
    }


}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier{% endblock %}
{% block icon %}
    <link rel="icon" type="image/png" size="32" href="https://img.icons8.com/3d-fluency/1500w/shopping-bag.png" data-hid="63b4eb3">
{% endblock %}

{% block body %}
    <div class="container py-5">
        <h1>Mon panier</h1>
        <div class="row">
            {% if cart|length > 0 %}
            <div class="col-md-8">

                Listes de produit
                <hr>
                {% for product in cart %}
                    <div class="row cart_product mb-2">
                        <div class="col-md-2 cart_product_image">
                            <img class="img-fluid" src="/uploads/{{ product['object'].image }}" alt="{{ product['object'].name }}">
                        </div>
                        <div class="col-md-4">
                            <strong>{{ product['object'].name }}</strong>
                            <small class="d-block">Prix unitaires: {{ product['object'].priceWt|formatPrice }}</small>
                        </div>
                        <div class="col-md-3 text-right">
                            <a href="{{ path('app_cart_decrease' , {id : product['object'].id }) }}">-</a> <span class="badge text-bg-secondary">x{{ product['quantity'] }}</span> <a href="{{ path('app_cart_increase' , {id : product['object'].id }) }}">+</a>
                        </div>
                        <div class="col-md-3 text-right">
                            <strong>{{ (product['object'].priceWt * product['quantity'])|formatPrice }}</strong>
                            <a href="{{ path('app_cart_remove', {id :  product['object'].id }) }}" class="btn btn-danger">Supprimer</a>
                        </div>
                    </div>
                {% endfor %}
                <a href="{{ path('app_cart_removeAll') }}" class="btn btn-danger">Vider votre panier</a>

            </div>
            <div class="col-md-4 p-3 bg-light">
                <div class=" d-flex justify-content-between">
                    <span>Total produit</span>
                    <span>{{ fullCartQuantity }}</span>
                </div>
                <div class="d-flex justify-content-between mt-3">
                    <span>Total Prix</span>
                    <span>{{ totalPriceWt|formatPrice }}</span>
                </div>
                <div>
                    <a href="{{ path('app_order') }}" class="btn btn-success w-100 mt-3 my_button">Commander</a>
                </div>
            </div>
        </div>
        {% else %}
            <p>Votre panier est vide.</p>
        {% endif %}
    </div>
{% endblock %}